# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include config/templates.yaml
shell_command:
  log_pool_temp: >
    python3 /config/pool_temp_logger.py
    "{{ states('sensor.omnilogic_pool_watersensor') }}"
    "{{ state_attr('weather.lake_ridge_dr', 'temperature') }}"
    "{{ states('water_heater.omnilogic_pool_heater') }}"
    "{{ states('switch.omnilogic_pool_filter_pump') }}"
    "{{ states('switch.omnilogic_pool_waterfall') }}"
    "{{ states('sensor.pool_forecast_high') }}"
    "{{ states('sensor.pool_swimming_day') }}"
  create_pool_temp_log: >
    python3 /config/pool_temp_logger.py "0" "0" "off" "off" "off" "0" "No"
